#!/bin/bash
# Axolotl QLoRA Training Script for Islamic AI
# Generated by Akhi CrewAI Dataset Preparer
# Date: 2025-07-31 09:53:27

set -e

echo "=== Akhi Islamic AI Training Pipeline ==="
echo "Config: axolotl_data/axolotl_config.yml"
echo "Dataset: 0 train, 1 val samples"
echo "Start time: $(date)"
echo "========================================="

# Check dependencies
echo "Checking dependencies..."
if ! python -c "import torch; print(f'PyTorch: {torch.__version__}')" 2>/dev/null; then
    echo "ERROR: PyTorch not found. Please install PyTorch first."
    exit 1
fi

if ! python -c "import transformers; print(f'Transformers: {transformers.__version__}')" 2>/dev/null; then
    echo "Installing transformers..."
    pip install transformers>=4.21.0
fi

if ! python -c "import axolotl" 2>/dev/null; then
    echo "Installing Axolotl..."
    pip install -e git+https://github.com/OpenAccess-AI-Collective/axolotl.git
fi

if ! python -c "import bitsandbytes" 2>/dev/null; then
    echo "Installing bitsandbytes for QLoRA..."
    pip install bitsandbytes
fi

echo "All dependencies satisfied."
echo ""

# Create models directory
mkdir -p axolotl_data/models

# Preprocess dataset
echo "Preprocessing dataset..."
python -m axolotl.cli.preprocess axolotl_data/axolotl_config.yml

if [ $? -ne 0 ]; then
    echo "ERROR: Dataset preprocessing failed!"
    exit 1
fi

echo "Dataset preprocessing completed successfully."
echo ""

# Start training
echo "Starting QLoRA training..."
echo "This may take several hours depending on your hardware..."
python -m axolotl.cli.train axolotl_data/axolotl_config.yml

if [ $? -ne 0 ]; then
    echo "ERROR: Training failed!"
    exit 1
fi

echo "Training completed successfully!"
echo ""

# Merge LoRA adapters
echo "Merging LoRA adapters..."
python -m axolotl.cli.merge_lora axolotl_data/axolotl_config.yml

if [ $? -ne 0 ]; then
    echo "WARNING: LoRA merge failed, but training was successful."
    echo "You can merge manually later using: python -m axolotl.cli.merge_lora axolotl_data/axolotl_config.yml"
else
    echo "LoRA adapters merged successfully!"
fi

echo ""
echo "========================================="
echo "🎉 TRAINING COMPLETED SUCCESSFULLY! 🎉"
echo "========================================="
echo "End time: $(date)"
echo "Model saved to: axolotl_data/models/"
echo "Training samples: 0"
echo "Validation samples: 1"
echo "Average input length: 2069.0 chars"
echo "Average output length: 1595.0 chars"
echo ""
echo "Next steps:"
echo "1. Test your model with sample inputs"
echo "2. Evaluate on validation set"
echo "3. Deploy to production"
echo "========================================="
