#!/usr/bin/env python3
"""
FAISS Storage Tool for Akhi CrewAI System

This tool provides FAISS vector database functionality for storing and managing
embeddings generated by the EmbedderTool. It supports index creation, embedding
storage with metadata, index persistence, and optimization.

Author: Akhi CrewAI Development Team
Date: 2024
"""

import os
import json
import pickle
import numpy as np
from typing import Dict, List, Any, Optional, Union, Tuple
from pathlib import Path
import logging
from datetime import datetime

try:
    import faiss
except ImportError:
    raise ImportError(
        "FAISS is required for vector storage. Install with: pip install faiss-cpu"
    )

from crewai.tools import BaseTool
from pydantic import BaseModel, Field, ConfigDict

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


class FAISSStoreInput(BaseModel):
    """Input schema for FAISS Storage Tool."""
    
    model_config = ConfigDict(arbitrary_types_allowed=True)
    
    embeddings: Union[List[List[float]], Any] = Field(
        description="List of embeddings or numpy array to store"
    )
    metadata: Optional[List[Dict[str, Any]]] = Field(
        default=None,
        description="Optional metadata for each embedding"
    )
    index_name: str = Field(
        default="default",
        description="Name of the FAISS index"
    )
    index_type: str = Field(
        default="flat",
        description="Type of FAISS index (flat, ivf, hnsw)"
    )
    dimension: Optional[int] = Field(
        default=None,
        description="Dimension of embeddings (auto-detected if not provided)"
    )
    save_index: bool = Field(
        default=True,
        description="Whether to save the index to disk"
    )
    index_dir: str = Field(
        default="akhi_crewai/data/embeddings",
        description="Directory to save FAISS indices"
    )
    overwrite: bool = Field(
        default=False,
        description="Whether to overwrite existing index"
    )
    nlist: int = Field(
        default=100,
        description="Number of clusters for IVF index"
    )
    m: int = Field(
        default=8,
        description="Number of subquantizers for PQ"
    )


class FAISSStoreOutput(BaseModel):
    """Output schema for FAISS Storage Tool."""
    
    success: bool = Field(description="Whether the operation was successful")
    index_name: str = Field(description="Name of the created/updated index")
    index_path: str = Field(description="Path to the saved index file")
    metadata_path: str = Field(description="Path to the saved metadata file")
    total_vectors: int = Field(description="Total number of vectors in the index")
    dimension: int = Field(description="Dimension of the vectors")
    index_type: str = Field(description="Type of FAISS index used")
    index_size_mb: float = Field(description="Size of the index file in MB")
    processing_time: float = Field(description="Time taken to process in seconds")
    message: str = Field(description="Status message")
    statistics: Dict[str, Any] = Field(description="Index statistics")


class FAISSStorageTool(BaseTool):
    """FAISS Storage Tool for vector database operations."""
    
    name: str = "FAISS Storage Tool"
    description: str = (
        "Store embeddings in FAISS vector database with metadata support. "
        "Supports multiple index types, persistence, and optimization."
    )
    args_schema: type = FAISSStoreInput
    indices: Dict[str, Any] = {}
    metadata_store: Dict[str, Dict[int, Dict[str, Any]]] = {}
    
    def __init__(self, **kwargs):
        """Initialize the FAISS Storage Tool."""
        super().__init__(**kwargs)
        if not hasattr(self, 'indices') or self.indices is None:
            self.indices = {}  # Cache for loaded indices
        if not hasattr(self, 'metadata_store') or self.metadata_store is None:
            self.metadata_store = {}  # Cache for metadata
        
    def _run(self, **kwargs) -> FAISSStoreOutput:
        """Execute the FAISS storage operation."""
        try:
            # Parse input
            input_data = FAISSStoreInput(**kwargs)
            start_time = self._get_current_time()
            
            # Validate and prepare embeddings
            embeddings_array = self._prepare_embeddings(input_data.embeddings)
            dimension = input_data.dimension or embeddings_array.shape[1]
            
            # Validate metadata
            metadata = self._validate_metadata(
                input_data.metadata, len(embeddings_array)
            )
            
            # Create or load index
            index = self._create_or_load_index(
                input_data.index_name,
                input_data.index_type,
                dimension,
                input_data.nlist,
                input_data.m,
                input_data.overwrite
            )
            
            # Add embeddings to index
            start_id = index.ntotal
            index.add(embeddings_array.astype(np.float32))
            
            # Store metadata
            self._store_metadata(
                input_data.index_name,
                metadata,
                start_id,
                len(embeddings_array)
            )
            
            # Save index if requested
            index_path, metadata_path = "", ""
            if input_data.save_index:
                index_path, metadata_path = self._save_index(
                    input_data.index_name,
                    index,
                    input_data.index_dir
                )
            
            # Calculate statistics
            processing_time = self._get_current_time() - start_time
            index_size_mb = self._calculate_index_size(index_path) if index_path else 0
            
            # Generate statistics
            statistics = self._generate_statistics(index, metadata)
            
            return FAISSStoreOutput(
                success=True,
                index_name=input_data.index_name,
                index_path=index_path,
                metadata_path=metadata_path,
                total_vectors=index.ntotal,
                dimension=dimension,
                index_type=input_data.index_type,
                index_size_mb=index_size_mb,
                processing_time=processing_time,
                message=f"Successfully stored {len(embeddings_array)} vectors in {input_data.index_name}",
                statistics=statistics
            )
            
        except Exception as e:
            logger.error(f"Error in FAISS storage: {str(e)}")
            return FAISSStoreOutput(
                success=False,
                index_name=kwargs.get('index_name', 'unknown'),
                index_path="",
                metadata_path="",
                total_vectors=0,
                dimension=0,
                index_type=kwargs.get('index_type', 'unknown'),
                index_size_mb=0,
                processing_time=0,
                message=f"Error: {str(e)}",
                statistics={}
            )
    
    def _prepare_embeddings(self, embeddings: Union[List[List[float]], np.ndarray]) -> np.ndarray:
        """Convert embeddings to numpy array and validate."""
        if isinstance(embeddings, list):
            embeddings_array = np.array(embeddings, dtype=np.float32)
        elif isinstance(embeddings, np.ndarray):
            embeddings_array = embeddings.astype(np.float32)
        else:
            raise ValueError(f"Unsupported embeddings type: {type(embeddings)}")
        
        if len(embeddings_array.shape) != 2:
            raise ValueError(f"Embeddings must be 2D array, got shape: {embeddings_array.shape}")
        
        if embeddings_array.shape[0] == 0:
            raise ValueError("No embeddings provided")
        
        return embeddings_array
    
    def _validate_metadata(self, metadata: Optional[List[Dict[str, Any]]], num_embeddings: int) -> List[Dict[str, Any]]:
        """Validate and prepare metadata."""
        if metadata is None:
            # Generate default metadata
            return [
                {
                    "id": i,
                    "timestamp": datetime.now().isoformat(),
                    "source": "unknown"
                }
                for i in range(num_embeddings)
            ]
        
        if len(metadata) != num_embeddings:
            raise ValueError(
                f"Metadata length ({len(metadata)}) must match embeddings length ({num_embeddings})"
            )
        
        # Ensure each metadata entry has required fields
        for i, meta in enumerate(metadata):
            if not isinstance(meta, dict):
                raise ValueError(f"Metadata entry {i} must be a dictionary")
            
            # Add default fields if missing
            if "id" not in meta:
                meta["id"] = i
            if "timestamp" not in meta:
                meta["timestamp"] = datetime.now().isoformat()
        
        return metadata
    
    def _create_or_load_index(self, index_name: str, index_type: str, dimension: int, 
                             nlist: int, m: int, overwrite: bool) -> faiss.Index:
        """Create a new FAISS index or load existing one."""
        # Check if index exists in cache
        if index_name in self.indices and not overwrite:
            logger.info(f"Using cached index: {index_name}")
            return self.indices[index_name]
        
        # Create new index based on type
        if index_type.lower() == "flat":
            index = faiss.IndexFlatIP(dimension)  # Inner product for cosine similarity
        elif index_type.lower() == "ivf":
            quantizer = faiss.IndexFlatIP(dimension)
            index = faiss.IndexIVFFlat(quantizer, dimension, nlist)
        elif index_type.lower() == "hnsw":
            index = faiss.IndexHNSWFlat(dimension, 32)  # 32 is M parameter
        elif index_type.lower() == "pq":
            index = faiss.IndexPQ(dimension, m, 8)  # 8 bits per subquantizer
        else:
            raise ValueError(f"Unsupported index type: {index_type}")
        
        # Cache the index
        self.indices[index_name] = index
        logger.info(f"Created new {index_type} index: {index_name} (dimension: {dimension})")
        
        return index
    
    def _store_metadata(self, index_name: str, metadata: List[Dict[str, Any]], 
                       start_id: int, count: int) -> None:
        """Store metadata for the embeddings."""
        if index_name not in self.metadata_store:
            self.metadata_store[index_name] = {}
        
        # Store metadata with vector IDs
        for i, meta in enumerate(metadata):
            vector_id = start_id + i
            self.metadata_store[index_name][vector_id] = meta
        
        logger.info(f"Stored metadata for {count} vectors in {index_name}")
    
    def _save_index(self, index_name: str, index: faiss.Index, index_dir: str) -> Tuple[str, str]:
        """Save FAISS index and metadata to disk."""
        # Create directory if it doesn't exist
        Path(index_dir).mkdir(parents=True, exist_ok=True)
        
        # Save FAISS index
        index_path = os.path.join(index_dir, f"{index_name}.faiss")
        faiss.write_index(index, index_path)
        
        # Save metadata
        metadata_path = os.path.join(index_dir, f"{index_name}_metadata.json")
        with open(metadata_path, 'w', encoding='utf-8') as f:
            json.dump(self.metadata_store.get(index_name, {}), f, indent=2, ensure_ascii=False)
        
        logger.info(f"Saved index to {index_path} and metadata to {metadata_path}")
        return index_path, metadata_path
    
    def _calculate_index_size(self, index_path: str) -> float:
        """Calculate the size of the index file in MB."""
        if not index_path or not os.path.exists(index_path):
            return 0.0
        
        size_bytes = os.path.getsize(index_path)
        return size_bytes / (1024 * 1024)  # Convert to MB
    
    def _generate_statistics(self, index: faiss.Index, metadata: List[Dict[str, Any]]) -> Dict[str, Any]:
        """Generate statistics about the index."""
        stats = {
            "total_vectors": index.ntotal,
            "dimension": index.d,
            "index_type": type(index).__name__,
            "is_trained": index.is_trained,
            "metric_type": "inner_product",
            "metadata_count": len(metadata)
        }
        
        # Add type-specific statistics
        if hasattr(index, 'nlist'):
            stats["nlist"] = index.nlist
        if hasattr(index, 'nprobe'):
            stats["nprobe"] = index.nprobe
        
        # Analyze metadata
        if metadata:
            sources = set()
            timestamps = []
            for meta in metadata:
                if "source" in meta:
                    sources.add(meta["source"])
                if "timestamp" in meta:
                    timestamps.append(meta["timestamp"])
            
            stats["unique_sources"] = len(sources)
            stats["sources"] = list(sources)
            if timestamps:
                stats["first_timestamp"] = min(timestamps)
                stats["last_timestamp"] = max(timestamps)
        
        return stats
    
    def _get_current_time(self) -> float:
        """Get current time for performance measurement."""
        return datetime.now().timestamp()
    
    def load_index(self, index_name: str, index_dir: str = "akhi_crewai/data/embeddings") -> bool:
        """Load an existing FAISS index from disk."""
        try:
            index_path = os.path.join(index_dir, f"{index_name}.faiss")
            metadata_path = os.path.join(index_dir, f"{index_name}_metadata.json")
            
            if not os.path.exists(index_path):
                logger.error(f"Index file not found: {index_path}")
                return False
            
            # Load FAISS index
            index = faiss.read_index(index_path)
            self.indices[index_name] = index
            
            # Load metadata if exists
            if os.path.exists(metadata_path):
                with open(metadata_path, 'r', encoding='utf-8') as f:
                    metadata = json.load(f)
                    # Convert string keys back to integers
                    self.metadata_store[index_name] = {
                        int(k): v for k, v in metadata.items()
                    }
            
            logger.info(f"Loaded index {index_name} with {index.ntotal} vectors")
            return True
            
        except Exception as e:
            logger.error(f"Error loading index {index_name}: {str(e)}")
            return False
    
    def list_indices(self, index_dir: str = "akhi_crewai/data/embeddings") -> List[str]:
        """List all available FAISS indices."""
        if not os.path.exists(index_dir):
            return []
        
        indices = []
        for file in os.listdir(index_dir):
            if file.endswith('.faiss'):
                index_name = file[:-6]  # Remove .faiss extension
                indices.append(index_name)
        
        return indices
    
    def get_index_info(self, index_name: str) -> Optional[Dict[str, Any]]:
        """Get information about a specific index."""
        if index_name not in self.indices:
            return None
        
        index = self.indices[index_name]
        metadata = self.metadata_store.get(index_name, {})
        
        return self._generate_statistics(index, list(metadata.values()))